### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by kokonut27** [CitricDevs/node#1]
Heyo!

> (it's me kokonut btw lol)

What's gonna be the purpose of this? Just curious of what your future goal is :D

**Comment by nodexninja** [comment]
We are probably going to be collaborating on projects in the future!

**Comment by kokonut27** [comment]
No no, like what’s the npm module’s purpose?

**Comment by darkdarcool** [comment]
I thought it was gonna be like a template for future packages in my opinion

**Comment by kokonut27** [comment]
Hmmm, maybe lol
